### ISSUE TITLE
CSS - make settings link change color on hover

### ISSUE THREAD

**Issue by cullub** [soscripted/sox#1]
Currently the achievements and messages icons change background color on hover, but the SOX settings link doesn't.  

![settingshover](https://cloud.githubusercontent.com/assets/7533931/13158160/4cc0ff2a-d651-11e5-9b4f-4a7f03d4ee9c.gif)

**Comment by cullub** [comment]
Recommended fix: 

 - Change inline `style` of `soxSettingsButton` to `background-image: none; padding: 10px 0 0 0; font-size: 14px; color: #999; height: 24px; width: 36px;` (note added height and widths)
 - Add class `yes-hover`

Tested to work in FF 44.0.2

**Comment by shu8** [comment]
@cullub thanks! Shouldn't be a problem; I'll look into this tomorrow

cc @enki-code :)

**Comment by shu8** [comment]
@cullub done :) thanks again!

**Comment by enki-code** [comment]
ahh... I forgot, it did that in my original script but must have been left out in the rewrite. Thanks @cullub .

**Comment by enki-code** [comment]
@shu8  Installed most recent dev version and this is still all screwy.
@cullub What are you using to create those gifs?

**Comment by enki-code** [comment]
@shu8  There is no css rule for 'sox-settings-button' did you forget to push changes? Looks like the yes-hover class needs to still be added?

![screwy](http://i.imgur.com/iSy8ZGo.png)

**Comment by shu8** [comment]
@enki-code and @cullub it's fixed now! It didn't work before because another commit I did overwrote and reversed the fix, as you can see at https://github.com/soscripted/sox/commits/dev/sox.css! whoops! Can you please confirm? (might need to wait a while for rawgit cache to delete)

**Comment by cullub** [comment]
I'm currently using the prod version, and it's not fixed yet...  Have you pushed to prod yet?

**Comment by shu8** [comment]
@cullub no.. it's still on dev. No idea when we should push to main branch. @enki-code any idea when??

**Comment by enki-code** [comment]
@shu8 Computer has been down for a couple of days, onboard lan port died while restarting my machine... lovely huh?    Since this is just a userscript, as long as a fix is *complete* I am fine with it being pushed to master.

**Comment by enki-code** [comment]
this issue is now resolved.
