### ISSUE TITLE
Mod diamonds don't show up in beta sites

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#102]
### Installed Version: 2.0.0  Environment: Tampermonkey 

...

###  Expected Behavior
A mod diamond would appear on every site
...

### Actual Behavior
Mod diamonds only appear on graduated sites, not beta sites.
...

### SOX Errors logged to the browser console (if available)

...

**Comment by shu8** [comment]
@IStoleThePies hmm, can't believe I missed this. will be fixed ASAP -- thanks for posting this! :)

**Comment by shu8** [comment]
@IStoleThePies Fixed in [v2.0.1g](https://github.com/soscripted/sox/raw/fix/sox.user.js) :) Thanks again!!

**Comment by IStoleThePies** [comment]
I just updated, and it still isn't showing up on beta sites.

**Comment by shu8** [comment]
@IStoleThePies I'm so sorry, I made a last minute change before I pushed and that broke it :/

Please could you reinstall from the same link above? It should hopefully work this time! :)

**Comment by IStoleThePies** [comment]
Works now, thanks! :D
