### ISSUE TITLE
Other reply button bugs

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#148]
### Installed Version: 2.0.2DEVv  Environment: Tampermonkey 

---

**Main issue**: Clicking "show x more comments" seems to make the reply buttons vanish on posts with enough comments (also happens if you try to add a comment, since this shows all of them). For example, see [here](http://astronomy.stackexchange.com/a/12856/9301).

Other strange issue(?): If you go to this [answer](http://astronomy.stackexchange.com/a/16287/9301) and click "show 4 more comments", one of them gets a scrollbar:

<img width="690" alt="screen shot 2016-11-19 at 4 38 54 pm" src="https://cloud.githubusercontent.com/assets/5375326/20458570/ba20da6a-ae76-11e6-804f-6f4963b66d20.png">

Clicking "add a comment" to show all of them doesn't make the scrollbar appear, and it only happens when SOX is running. My window size is "1440 x 733". I'm not sure if this will be a problem for anything in the future, but thought I might as well point it out.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by shu8** [comment]
@IStoleThePies I've fixed the main issue about the reply buttons disappearing in [dev w](https://github.com/soscripted/sox/raw/dev/sox.user.js).

However, I can't reproduce your scrollbar issue, but, I've added a CSS change that should stop it from appearing nonetheless. Can you check to see if you still see the scrollbar?

**Comment by IStoleThePies** [comment]
@shu8 Yep, it's gone :)

**Comment by IStoleThePies** [comment]
@shu8 Still appears on some comments:

<img width="657" alt="screen shot 2016-11-25 at 10 58 48 pm" src="https://cloud.githubusercontent.com/assets/5375326/20635853/38133c56-b363-11e6-8034-1ea888d0c076.png">

Confirmed again it's caused by SOX 😕
