### ISSUE TITLE
Comment scores missing

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#191]
### Current Behaviour
Another feature has suddenly disappeared (must have a common denominator).  The comment score are missing on the profile page.

---

### SOX Errors logged to the browser console -- F12 (if available)
Likely the same cause as other features that also suddenly went missing when something unrelated got changed in a recent version.  

Just refreshed the page to capture console output and that restored the comment scores.  The page had already been refreshed and the scores were still missing.  So maybe a timing issue, or something in the logging routine affected it?

Update: the buttons are back, but clicking them doesn't do anything.  I'll post some console output:

```
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:6864
GET 
http://superuser.com/users/364367/fixer1234 [HTTP/1.1 200 OK 104ms]
GET 
https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js [HTTP/2.0 304 Not Modified 14ms]
GET 
https://cdn.sstatic.net/Js/stub.en.js [HTTP/2.0 304 Not Modified 11ms]
GET 
https://cdn.sstatic.net/Sites/superuser/all.css [HTTP/2.0 304 Not Modified 13ms]
GET 
https://cdn.sstatic.net/Js/third-party/d3.v3.min.js [HTTP/2.0 304 Not Modified 13ms]
GET 
https://cdn.sstatic.net/Js/image-upload.en.js [HTTP/2.0 304 Not Modified 13ms]
GET 
https://cdn.sstatic.net/Js/user.en.js [HTTP/2.0 304 Not Modified 13ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.v3.min.js:3:2131
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 25ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 17ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 30ms]
GET 
https://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/2.0 304 Not Modified 22ms]
GET 
https://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/2.0 304 Not Modified 12ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 21ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 16ms]
SOX:  undefined sox.common.js:16:13
SOX:  Object { init: StackExchange.init</<(n, s), debug: Object, initialized: Object, ready: StackExchange.ready(e), using: v(e, n, i, r), ifUsing: b(e, t, n), loadJsFile: StackExchange.loadJsFile(e, t), loadJqueryUi: StackExchange.loadJqueryUi(), helpers: Object, switchMobile: StackExchange.switchMobile(e), 7 more… } sox.common.js:16:13
SOX:  DEBUGGING SOX VERSION 2.0.3 DEV k sox.common.js:16:13
SOX:  ----------------saved variables--------------------- sox.common.js:16:13
SOX:  logging sox stored values ---  sox.common.js:40:13
SOX:  access token set sox.common.js:40:13
SOX:  SOX-debug sox.common.js:40:13
SOX:  true sox.common.js:40:13
SOX:  SOXSETTINGS sox.common.js:40:13
SOX:  ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"] sox.common.js:40:13
SOX:  editReasons sox.common.js:40:13
SOX:  [["formatting","Improved Formatting"],["spelling","Corrected Spelling"],["grammar","Fixed grammar"],["greetings","Removed thanks/greetings"]] sox.common.js:40:13
SOX:  metaNewQuestionAlert-lastQuestions sox.common.js:40:13
SOX:  {"meta.superuser":"Show your Excel results"} sox.common.js:40:13
SOX:  ----------------end saved variables--------------------- sox.common.js:16:13
GET 
https://cdn.sstatic.net/img/favicons-sprite16.png [HTTP/2.0 304 Not Modified 14ms]
GET 
https://cdn.sstatic.net/Img/user-profile-graph.svg [HTTP/2.0 304 Not Modified 14ms]
GET 
https://cdn.sstatic.net/Img/user-profile-sprite.svg [HTTP/2.0 304 Not Modified 17ms]
GET 
https://cdn.sstatic.net/img/user-profile-sprite.svg [HTTP/2.0 304 Not Modified 18ms]
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 18ms]
GET 
https://cdn.sstatic.net/Js/full.en.js [HTTP/2.0 304 Not Modified 13ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:72:0
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 13ms]
SOX:  initializing SOX dialog sox.common.js:16:13
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 17ms]
GET 
http://pixel.quantserve.com/pixel;r=924343012;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1482699317612;tzo=300;ref=http%3A%2F%2Fsuperuser.com%2Fusers%2F364367%2Ffixer1234%3Ftab%3Dsummary;url=http%3A%2F%2Fsuperuser.com%2Fusers%2F364367%2Ffixer1234%3Ftab%3Dactivity;ogl=type.website%2Cimage.https%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e445943%2Ctitle.User%20fixer1234%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fusers%2F364367%2Ffixer1234 [HTTP/1.1 200 OK 33ms]
SOX:  injecting features into dialog sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  addAuthorNameToInboxNotifications sox.common.js:16:13
SOX:  Object { name: "addAuthorNameToInboxNotifications", desc: "Add the author's name to notificati…", extended_description: "If you receive a comment/answer/sug…", meta: "", match: "", exclude: "" } sox.common.js:16:13
SOX:  running addAuthorNameToInboxNotifications sox.common.js:16:13
SOX:  observe: .inbox-dialog sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  alignBadgesByClass sox.common.js:16:13
SOX:  Object { name: "alignBadgesByClass", desc: "Align badges by their class on user…", meta: "http://meta.stackexchange.com/q/254…", match: "*://*/users/*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running alignBadgesByClass sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  answerTagsSearch sox.common.js:16:13
SOX:  Object { name: "answerTagsSearch", desc: "Show tags for the question an answe…", meta: "http://meta.stackexchange.com/quest…", match: "*://*.com/search*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  colorAnswerer sox.common.js:16:13
SOX:  Object { name: "colorAnswerer", desc: "Color answerer's comments", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  fixedTopbar sox.common.js:16:13
SOX:  Object { name: "fixedTopbar", desc: "Fix topbar position", extended_description: "Locks the topbar to the top of the …", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "", settings: Array[1] } sox.common.js:16:13
SOX:  running fixedTopbar sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  isQuestionHot sox.common.js:16:13
SOX:  Object { name: "isQuestionHot", desc: "Add a label on questions which are …", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  markEmployees sox.common.js:16:13
SOX:  Object { name: "markEmployees", desc: "Add the SO logo after employee name…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running markEmployees sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  metaChatBlogStackExchangeButton sox.common.js:16:13
SOX:  Object { name: "metaChatBlogStackExchangeButton", desc: "Show meta and chat buttons on hover…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "" } sox.common.js:16:13
SOX:  running metaChatBlogStackExchangeButton sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  metaNewQuestionAlert sox.common.js:16:13
SOX:  Object { name: "metaNewQuestionAlert", desc: "Add a mod diamond to the topbar to …", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running metaNewQuestionAlert sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  scrollToTop sox.common.js:16:13
SOX:  Object { name: "scrollToTop", desc: "Add Scroll To Top button", extended_description: "This feature adds a 'scroll to top'…", meta: "", match: "", exclude: "*://chat.*.com/*" } sox.common.js:16:13
SOX:  running scrollToTop sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  standOutDupeCloseMigrated sox.common.js:16:13
SOX:  Object { name: "standOutDupeCloseMigrated", desc: "Add highlighted tags to closed/on h…", extended_description: "Adds a coloured box at the end of a…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running standOutDupeCloseMigrated sox.common.js:16:13
SOX:  observe: #user-tab-questions, #question-mini-list sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Appearance sox.common.js:16:13
SOX:  tabularReviewerStats sox.common.js:16:13
SOX:  Object { name: "tabularReviewerStats", desc: "Display reviewer stats on /review/s…", meta: "http://meta.stackexchange.com/q/276…", match: "*://*.com/review/suggested-edits/*", exclude: "" } sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  autoShowCommentImages sox.common.js:16:13
SOX:  Object { name: "autoShowCommentImages", desc: "View linked images (to imgur) in co…", meta: "", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  commentReplies sox.common.js:16:13
SOX:  Object { name: "commentReplies", desc: "Add reply links to comments for qui…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  commentShortcuts sox.common.js:16:13
SOX:  Object { name: "commentShortcuts", desc: "Use Ctrl+I,B,K (to italicise, bolde…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  confirmNavigateAway sox.common.js:16:13
SOX:  Object { name: "confirmNavigateAway", desc: "Add a confirmation dialog when navi…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  showCommentScores sox.common.js:16:13
SOX:  Object { name: "showCommentScores", desc: "Show your comment and comment repli…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/users/*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  running showCommentScores sox.common.js:16:13
SOX:  observe: #user-tab-responses, #user-tab-activity sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Comments sox.common.js:16:13
SOX:  hiddenCommentsIndicator sox.common.js:16:13
SOX:  Object { name: "hiddenCommentsIndicator", desc: "Add a darker border underneath comm…", meta: "http://meta.stackoverflow.com/q/296…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  addSBSBtn sox.common.js:16:13
SOX:  Object { name: "addSBSBtn", desc: "Add a button to the editor toolbar …", extended_description: "An 'SBS' button is added to the rig…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running addSBSBtn sox.common.js:16:13
SOX:  observe: li[id^="wmd-redo-button"] sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  observe: .wmd-preview.sbs-on sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  editComment sox.common.js:16:13
SOX:  Object { name: "editComment", desc: "Pre-defined edit comment options (c…", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running editComment sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  editReasonTooltip sox.common.js:16:13
SOX:  Object { name: "editReasonTooltip", desc: "Add a tooltip to posts showing the …", extended_description: "When a post is edited, the editor i…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  enhancedEditor sox.common.js:16:13
SOX:  Object { name: "enhancedEditor", desc: "Add more features to the markdown e…", meta: "", match: "*://*/questions*,*://*/review*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  kbdAndBullets sox.common.js:16:13
SOX:  Object { name: "kbdAndBullets", desc: "Add KBD and list buttons to editor …", meta: "http://meta.stackexchange.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running kbdAndBullets sox.common.js:16:13
SOX:  observe: [id^="wmd-redo-button"] sox.common.js:16:13
SOX:  undefined sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  titleEditDiff sox.common.js:16:13
SOX:  Object { name: "titleEditDiff", desc: "Make title edits show separately ra…", meta: "http://meta.stackexchange.com/quest…", match: "*://*.com/review/suggested-edits*", exclude: "" } sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  inlineEditorEverywhere sox.common.js:16:13
SOX:  Object { name: "inlineEditorEverywhere", desc: "Inline editor regardless of reputat…", extended_description: "Enables the inline editor on all si…", meta: "", match: "*://*/questions*", exclude: "" } sox.common.js:16:13
SOX:  Editing sox.common.js:16:13
SOX:  downvotedPostsEditAlert sox.common.js:16:13
SOX:  Object { name: "downvotedPostsEditAlert", desc: "Add a notification to your inbox wh…", meta: "http://meta.stackexchange.com/q/165…", match: "", exclude: "" } sox.common.js:16:13
SOX:  running downvotedPostsEditAlert sox.common.js:16:13
SOX:  downvotedPostsEditAlert posts to check sox.common.js:16:13
SOX:  Object {  } sox.common.js:16:13
SOX:  downvotedPostsEditAlert notifications sox.common.js:16:13
SOX:  Object {  } sox.common.js:16:13
SOX:  Flags sox.common.js:16:13
SOX:  flagOutcomeTime sox.common.js:16:13
SOX:  Object { name: "flagOutcomeTime", desc: "Show the flag outcome time when vie…", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running flagOutcomeTime sox.common.js:16:13
SOX:  Flags sox.common.js:16:13
SOX:  flagPercentages sox.common.js:16:13
SOX:  Object { name: "flagPercentages", desc: "Show flagging percentages for each …", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running flagPercentages sox.common.js:16:13
SOX:  Flags sox.common.js:16:13
SOX:  flagPercentageBar sox.common.js:16:13
SOX:  Object { name: "flagPercentageBar", desc: "Show the total percentage of helpfu…", meta: "http://meta.stackoverflow.com/quest…", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running flagPercentageBar sox.common.js:16:13
SOX:  Sidebar sox.common.js:16:13
SOX:  hideHireMe sox.common.js:16:13
SOX:  Object { name: "hideHireMe", desc: "Hide the Looking for a Job module", meta: "", match: "", exclude: "*://chat.*.com/*" } sox.common.js:16:13
SOX:  running hideHireMe sox.common.js:16:13
SOX:  Sidebar sox.common.js:16:13
SOX:  linkedToFrom sox.common.js:16:13
SOX:  Object { name: "linkedToFrom", desc: "Add an arrow to linked posts in the…", meta: "http://meta.stackexchange.com/q/276…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Chat sox.common.js:16:13
SOX:  chatEasyAccess sox.common.js:16:13
SOX:  Object { name: "chatEasyAccess", desc: "Add buttons to user profiles to cha…", meta: "http://meta.stackexchange.com/q/203…", match: "*://chat.*.com/*", exclude: "" } sox.common.js:16:13
SOX:  Chat sox.common.js:16:13
SOX:  replyToOwnChatMessages sox.common.js:16:13
SOX:  Object { name: "replyToOwnChatMessages", desc: "Add reply signs to your own chat me…", meta: "", match: "*://chat.*.com/*", exclude: "" } sox.common.js:16:13
SOX:  Chat sox.common.js:16:13
SOX:  renameChat sox.common.js:16:13
SOX:  Object { name: "renameChat", desc: "Prepend 'Chat - ' to chat tabs' tit…", meta: "http://meta.stackexchange.com/quest…", match: "*://chat.*.com/*", exclude: "" } sox.common.js:16:13
SOX:  Voting sox.common.js:16:13
SOX:  grayOutVotes sox.common.js:16:13
SOX:  Object { name: "grayOutVotes", desc: "Gray out deleted vote buttons", meta: "http://meta.stackexchange.com/a/174…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Voting sox.common.js:16:13
SOX:  disableOwnPostVoteButtons sox.common.js:16:13
SOX:  Object { name: "disableOwnPostVoteButtons", desc: "Disable vote buttons on your own po…", meta: "", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  alwaysShowImageUploadLinkBox sox.common.js:16:13
SOX:  Object { name: "alwaysShowImageUploadLinkBox", desc: "Always show the 'Link from the web'…", extended_description: "Removes the 'you can also provide a…", meta: "http://meta.stackoverflow.com/q/306…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  linkedPostsInline sox.common.js:16:13
SOX:  Object { name: "linkedPostsInline", desc: "Display linked posts inline by clic…", meta: "", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  parseCrossSiteLinks sox.common.js:16:13
SOX:  Object { name: "parseCrossSiteLinks", desc: "Parse titles to links cross-SE-sites", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  quickAuthorInfo sox.common.js:16:13
SOX:  Object { name: "quickAuthorInfo", desc: "Show when the post's author was las…", meta: "", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  shareLinksMarkdown sox.common.js:16:13
SOX:  Object { name: "shareLinksMarkdown", desc: "Change 'share' link to format of [p…", extended_description: "When you click 'share' under a post…", meta: "http://meta.stackexchange.com/quest…", match: "*://*/questions*", exclude: "SE1.0" } sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  warnNotLoggedIn sox.common.js:16:13
SOX:  Object { name: "warnNotLoggedIn", desc: "Warn you when you are not logged in", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0" } sox.common.js:16:13
SOX:  running warnNotLoggedIn sox.common.js:16:13
SOX:  Unsorted sox.common.js:16:13
SOX:  showMetaReviewCount sox.common.js:16:13
SOX:  Object { name: "showMetaReviewCount", desc: "Add how many reviews are available …", meta: "", match: "*://*/review", exclude: "*://meta.*.com/*" } sox.common.js:16:13
GET 
http://cdn-prom.sstatic.net/WinterBash/js/qa-wb.js [HTTP/1.1 304 Not Modified 47ms]
GET 
XHR 
http://superuser.com/users/ivc/364367/8f8f [HTTP/1.1 204 No Content 38ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 28ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/ [HTTP/1.1 400 Bad Request 26ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 48ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 121ms]
GET 
http://cdn-prom.sstatic.net/WinterBash/css/wb-include.css [HTTP/1.1 304 Not Modified 21ms]
GET 
http://cdn-prom.sstatic.net/WinterBash/js/theactualhats.js [HTTP/1.1 304 Not Modified 23ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 101ms]
GET 
http://winterbash2016.stackexchange.com/api/hat-count [HTTP/1.1 200 OK 45ms]
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 21ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 27ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 23ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 22ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 36ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 34ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 32ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 71ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 70ms]


This is where the output ended after refreshing the page.  I then clicked several comment buttons, and each time generated the roughly half a dozen lines replicated below.


SOX:  SOX Access Token: SET sox.common.js:16:13
SOX:  "Getting From API with URL: https://api.stackexchange.com/2.2/comments/1670710?order=desc&sort=creation&site=superuser&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=WjWFXV(FnEUlw4yD*Gkgkg))" sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:2:40351
GET 
XHR 
https://api.stackexchange.com/2.2/comments/1670710 [HTTP/1.1 400 Bad Request 78ms]
GET 
XHR 
http://superuser.com/users/364367/fixer1234 [HTTP/1.1 200 OK 100ms]
SOX:  SOX Error: error Bad Request sox.common.js:34:13

SOX:  SOX Access Token: SET sox.common.js:16:13
SOX:  "Getting From API with URL: https://api.stackexchange.com/2.2/comments/1670687?order=desc&sort=creation&site=superuser&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=WjWFXV(FnEUlw4yD*Gkgkg))" sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
GET 
XHR 
https://api.stackexchange.com/2.2/comments/1670687 [HTTP/1.1 400 Bad Request 26ms]
GET 
XHR 
http://superuser.com/users/364367/fixer1234 [HTTP/1.1 200 OK 76ms]
SOX:  SOX Error: error Bad Request sox.common.js:34:13

SOX:  SOX Access Token: SET sox.common.js:16:13
SOX:  "Getting From API with URL: https://api.stackexchange.com/2.2/comments/1670676?order=desc&sort=creation&site=superuser&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=WjWFXV(FnEUlw4yD*Gkgkg))" sox.common.js:16:13
SOX:  SOX Access Token: SET sox.common.js:16:13
GET 
XHR 
https://api.stackexchange.com/2.2/comments/1670676 [HTTP/1.1 400 Bad Request 75ms]
GET 
XHR 
http://superuser.com/users/364367/fixer1234 [HTTP/1.1 200 OK 85ms]
SOX:  SOX Error: error Bad Request sox.common.js:34:13

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```

---

### Steps to reproduce
This may be tough to diagnose since it can't be reproduced on command.  Maybe fixing the underlying problem via solution to another bug will take care of this.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"]

**Comment by shu8** [comment]
@fixer1234 looks like an access token issue -- it says 'key is not valid for passed access token' -- is this the machine you last got an access token for?

I'm sorry I have to keep asking you to do this, but you'll need to reset SOX again to get a new access token :(

---

BTW, I am thinking of having an option where you can 'backup' your settings so when you reset you can paste them back in -- I'm just thinking of how to do it in the UI, so if you have any ideas on what it could look like/where to place the button, I'm all ears :)

**Comment by fixer1234** [comment]
@shu8 This is on the machine that I reset and got a new token.  It's possible that I also used SOX on another machine that was still using the old token.  Could that be the problem?  If so, how do I use SOX on multiple machines?  Is the token tied to the machine or the SE account?

It looks like you were right about the cause.  I installed dev M, reset the account, got a new token, and now comment scores are working properly again.  I'll close this issue.

re: saving preferences--that would be the second best thing since sliced bread.  I think the only time it comes into play is when SOX is reinstalled.  A logical UI for me would be to automatically backup settings when they change.  When SOX is installed, have a button, that is part of the installation, to decline re-use of the old settings (otherwise, automatically re-use them).  Actually, I can't imagine someone not wanting the old settings as a starting point, so maybe you don't even need the decline option.   Use the Nike approach: just do it. 

If the new SOX version contains a new feature, it would need to recognize that and either warn the user to manually set that preference, or present just that feature at that point in the installation for the user to set it.  Variation or associated with the first approach: in the list of settings, highlight any new feature that didn't get a saved setting until the user clicks the save settings button.  That would make it easy to spot what needs review/action.

**Comment by shu8** [comment]
@fixer1234 so this what I was saying about the textfield that I'm going to add that will allow you to paste in an access token so you can use it on multiple computers/browsers.

It should be ready soon...

thanks for the suggestion, but I don't think that'll work because if you either delete and reinstall or reset sox then all settings are erased, and we can't have any say over keeping any of them -- that's all TM/GM so I think I'll add a small icon (a keyboard icon maybe?) somewhere that opens a prompt to paste in a list..

**Comment by fixer1234** [comment]
@shu8 "Backup" is the operative word.  Store a backup of the settings somewhere outside of SOX (like a cookie?).  But if that isn't possible, something like you propose to manually save the settings to, say, your own text file, and a way to paste them back would still work.  It would still need to advise the user about new features not included in the saved settings.

re: tokens--I do have multiple computers with SOX loaded.  Are you saying that I need to remove SOX from all but one for now; that opening SOX on another computer will corrupt the token?  How am I supposed to survive without SOX on every computer?

**Comment by shu8** [comment]
you can open SOX on multiple computers, just make sure you don't allow that
popup to open that gets another access token.

I'm working on the paste-in thing now, should be ready by at the latest
wednesday, depending on whether I run into any problems...

**Comment by shu8** [comment]
@fixer1234 turns out it was pretty simple :P 

you can now paste in an access token in [dev o](https://github.com/soscripted/sox/raw/dev/sox.user.js).

Here's what I suggest you do:

- on your main computer/browser, reset SOX (last time hopefully)!
- let the popup show and let it save the access token
- don't close the popup: copy and paste the access token somewhere/email it to yourself
- on all other computers/browsers, install dev O and then click the little key icon at the bottom of the dialog and paste in the access token

Now all the features should work on all the computers/browsers :)

An annoying thing is though, that if you ever get a new access token, you'll need to repeat this process on all computers. 

However, I've read that there is a 'sync' option available in GM, which you could possible look into so settings are synced across all Firefox installations you have, but I'm not sure if sync works anymore on FF because I've seen a lot of issues about it :/

**Comment by fixer1234** [comment]
@shu8 Are you planning to wait until SOX is perfect before implementing a way to save the settings?  That sure would be handy now.  Just sayin'.

**Comment by shu8** [comment]
Lol it's a work in progress.. need to work out a few problems ;(

**Comment by fixer1234** [comment]
@shu8 Comment score was previously working automatically on comment history pages after the first.  At one point prior to polishing that feature, pages after the first required a page refresh to display the buttons.  I'm running Dev N and found that the requirement to refresh pages after the first is again haunting SOX.  So whatever you did before to fix it, do that again.

**Comment by shu8** [comment]
@fixer1234 fixed in [dev p](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 The issue of requiring a page refresh for pages after the first still exists in Dev P.

**Comment by shu8** [comment]
@fixer1234 hehe funny story... I kinda removed the call (see [the revision](https://github.com/soscripted/sox/commit/818ae9ef7d7bc69ec349fa52fb68bde582b2a035#diff-7060b232c66b79b305b21dd6bc7a51a4L142)) to call the function after all mutationobservers :/

Sorry, fixed in [dev q](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Confirmed.  Full functionality back in Dev Q.

**Comment by fixer1234** [comment]
@shu8 Question on the tokens.  Each time SOX is reinstalled, it creates a new token.  It isn't clear what's really required.

- Under what circumstances does SOX need to be removed from the user profile before getting a new token?

- Installing SOX automatically runs the get-token sequence.  How does using the new key icon relate to that?  (suppresses getting a new key?  Puts the old key back after getting a new key?)

- What's the procedure for using that feature?

- What's the relationship between tokens on different machines and what was the problem condition associated with that?

- Under what conditions can I continue to use different tokens on different machines and under what conditions do I need to install matching tokens?

- If I've coordinated tokens across different machines and then install a new SOX version on one machine, should I install the old, matching token on the new SOX installation?

- Is there any unique relationship between a specific token and a SOX version?  Any specific settings or info associated with the token that could be incompatible between SOX versions or across platforms?

**Comment by shu8** [comment]
> Under what circumstances does SOX need to be removed from the user profile before getting a new token?

SOX shouldn't need to be removed at all really. When a new (either dev or official) version comes out, all you need to do is reinstall **without** uninstalling the previous version. GM/TM will let you 'update' the script keeping all settings intact.

> Installing SOX automatically runs the get-token sequence. How does using the new key icon relate to that? (suppresses getting a new key? Puts the old key back after getting a new key?)

The new key icon allows you to paste in an access token so you can use the same access token on multiple machines

> What's the procedure for using that feature?

Clicking it will allow you to paste the access token in, and it will be saved

> What's the relationship between tokens on different machines and what was the problem condition associated with that?

The SE API doesn't allow for 1 user to have multiple access tokens for a single application. So, each time a new access token is requested, all others are automatically invalidated. **Only the latest access token is ever valid**.

> Under what conditions can I continue to use different tokens on different machines and under what conditions do I need to install matching tokens?

You can never use different access tokens. You need to always use matching tokens

> If I've coordinated tokens across different machines and then install a new SOX version on one machine, should I install the old, matching token on the new SOX installation?

If you *update* rather than delete then install again, then all the settings should remain saved and you shouldn't need to do anything extra

> Is there any unique relationship between a specific token and a SOX version? Any specific settings or info associated with the token that could be incompatible between SOX versions or across platforms?

No

**Comment by fixer1234** [comment]
@shu8 Thanks.  If I had known about the ability to simply update, hours would been saved.  You might want to mention that on the home page.  :-)

Follow-up:

- A couple of times, you had me remove SOX from the profile.  Was that just to ensure a clean installation when you thought the issue might have been token-related?

- I've had SOX on multiple machines pretty much since I started using it.  It has almost never had the same version on two machines, and I have always reinstalled from scratch.  So the tokens have always been different on the different machines, and all of the features have worked (except when they didn't, but that hasn't generally been token-related, except in the few cases where it was).  I often have sessions open on two machines concurrently, using different tokens, and don't encounter features not working.

   What do you expect is/should be happening in this situation?  Each machine ignores the other?  Each machine keeps invalidating the other token in ping pong fashion?  Both tokens are accepted despite supposedly not being possible?  The system with the older token has missing features that I simply haven't noticed?  That would be easy to verify--which features require the token?

**Comment by shu8** [comment]
@fixer1234 a bit late...

- yeah, that was just to ensure it was completely clean
- it could be that I was wrong now that the token issue is fixed; maybe you *can* use multiple tokens. I had only assumed that was the case because whenever I tried, the other machine token died, but it may well have been 24 hours apart. could you try requesting separate tokens in the latest version on different machines and seeing if all the features work?
- I'm not sure anymore... the above will help figure it out.

**Comment by fixer1234** [comment]
@shu8 Dev AD on main machine with a new token,  Started an additional session on another machine while the first was idle.  Loaded Dev AD on the second machine (which had an expired token).  As previously tested, the SOX "key" didn't work to load the token from the first machine (paste the key, save, refresh; still behaved like no valid token).  Generated a new token on the second machine.  

Later returned to the first machine and refreshed the SU tabs.  Checked a thread to see if Author last seen was displayed, which it was.  So it still reflects a valid (older) token.  This is consistent with earlier experience where the tokens on different machines seemed to be independent.

**Comment by shu8** [comment]
@fixer1234 OK! seems like we *can* use multiple access tokens!

Sorry for the confusion; completely my fault. 😞
