### ISSUE TITLE
SOX HTTPS issues

### ISSUE THREAD

**Issue by shu8** [soscripted/sox#266]
This Meta post [Network-wide HTTPS: It's time](https://meta.stackexchange.com/q/292058/260841) shows that SE are now moving to HTTPS, so we need to make sure no links are HTTP throughout SOX now.

List of things to check (please add some if you can think of any):

- [x] API Requests
- [x]  `@require`d URLs
- [x] image URLs

**Comment by j-f1** [comment]
* image URLs

**Comment by shu8** [comment]
@j-f1 thanks, I've added that to the list and changed to use task lists :)

**Comment by shu8** [comment]
Done in [dev 2.0.28](https://github.com/soscripted/sox/raw/dev/sox.user.js).

Please comment here if you see any HTTPS warnings in the console! :)

**Comment by SathyaBhat** [comment]
On questions which have been edited, https/mixed mode errors are still shown

Ex URL: https://superuser.com/questions/1235710/access-crontab-process-in-a-terminal-using-ssh

> Refused to connect to 'http://superuser.com/posts/1235710/revisions' because it violates the following Content Security Policy directive: "default-src https: wss: data: blob: 'unsafe-eval' 'unsafe-inline'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

> Mixed Content: The page at 'https://superuser.com/questions/1235710/access-crontab-process-in-a-terminal-using-ssh' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://superuser.com/posts/1235710/revisions'. This request has been blocked; the content must be served over HTTPS.

I guess it comes from here https://github.com/soscripted/sox/blob/master/sox.features.js#L1034

**Comment by shu8** [comment]
@SathyaBhat Thanks for bringing that up! I'm away for a few weeks but I'll get this fixed ASAP! :)

**Comment by shu8** [comment]
@SathyaBhat should be fixed in [dev 2.0.39](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) sorry for the delay!

**Comment by SathyaBhat** [comment]
No problem. thanks for fixing
