### ISSUE TITLE
Edit box features not working

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#72]
**Installed Version: 2.0.0  |  Environment: undefined**

**Expected Behavior**

> Have SBS, KBD/Bullet list, and Find&Replace/Autocorrect features enabled in SOX

**Actual Behavior**

> How is the feature currently behaving?
> Answer Edit Window:

![edit box 2](https://cloud.githubusercontent.com/assets/10065766/16542136/121910e6-406a-11e6-9154-be06899221d5.png)

Only Find&Replace/Autocorrect included

Question Edit Window:

![edit box 1](https://cloud.githubusercontent.com/assets/10065766/16542143/3f3ced72-406a-11e6-9484-ca878f1614c4.png)

None of these features included

**Error Logs**

> SOX errors are logged to the browser console, if possible, please post those here.

```
SOX:  initializing SOX dialog sox.common.js:54:17
SOX:  injecting features into dialog sox.common.js:54:17
SOX:  Please go to stackoverflow.com to get your access token for certain SOX features sox.common.js:54:17
Content Security Policy: The page's settings blocked the loading of a resource at about:blank ("base-uri https://github.com"). <unknown>
Empty string passed to getElementById(). github-06ce76d6a7511ce3a2095752c3575119026281a84f0c9ca9fe739b7317c949c5.js:6:26892
vwof plugin, exception in ScreenWaveMedia: TypeError: video_data is undefined vwof.js:67:0
Empty string passed to getElementById(). frameworks-f2de4c863a487a877150989f965232bacfde178abf9c1963d9f84c5c19916f0c.js:9:20031
TypeError: NetworkError when attempting to fetch resource. <unknown>
ReferenceError: assignment to undeclared variable $that sox.enhanced_editor.js:13:29
SOX:  initializing SOX dialog sox.common.js:54:17
SOX:  injecting features into dialog sox.common.js:54:17
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:6598
no element found fa91:1:1
SOX:  Please go to stackoverflow.com to get your access token for certain SOX features sox.common.js:54:17
vwof plugin, exception in ScreenWaveMedia: TypeError: video_data is undefined vwof.js:67:0
ReferenceError: waitForKeyElements is not defined sox.features.js:1016:25
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
no element found github-cloud.s3.amazonaws.com:1:1
Content Security Policy: The page's settings blocked the loading of a resource at https://github-cloud.s3.amazonaws.com/ ("base-uri https://github.com"). <unknown>
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
no element found github-cloud.s3.amazonaws.com:1:1
ReferenceError: assignment to undeclared variable $that sox.enhanced_editor.js:13:29
Use of getAttributeNode() is deprecated. Use getAttribute() instead. jquery.min.js:2:29939
TypeError: keyset is null bootstrap.js:34:5
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```

**Steps to reproduce**

> What steps did you take to reproduce the issue?
> Accessed edit windows.

Note: I uninstalled the previous version and installed this one (with restarts in between), so there were no differences in add-ons.  The edit features worked in the previous version.

**Comment by enki-code** [comment]
I can confirm that this works fine on Chrome but not on Firefox.   TBH, it might be a week or so before I can really dig into all of this.  If it is too much, feel free to downgrade back to v1.0.3.

I apologize for the inconvenience.

**Comment by fixer1234** [comment]
The "developmental" v1.0.4 fixed some problems with key features not working in v1.0.3.  It looks like V1.0.4 has been removed, and I found a source code link for v1.0.3, but not an installable version.  Any chance of putting the v1.0.4 installer back temporarily?

**Comment by enki-code** [comment]
Unfortunately, when we release each version the dev version isn't included in the release. After moving to 2.0 the developmental branch was updated to with the new version. So, ATM I don't have access to the 1.0.4 DEV version. 

I might have a copy locally or @shu8 might. 

Again, sorry, this is has been a complete mess, not to make excuses but I've been extremely distracted lately, my wife is pregnant and things have been crazy.

**Comment by fixer1234** [comment]
Not to worry.  The distractions will totally end after your wife delivers.  :-)

**Comment by enki-code** [comment]
@fixer1234 I did some digging this morning and my local copy of SOX still had the 1.0.4 DEV branch, thankfully.

You can install it from [here](https://gist.github.com/enki-code/392a8c90cc3f5e6287a85a3d4eb54d98/raw/7c73eb59c7b1d2133a2b1d0e3ac0cf5bda60c2bd/sox.old.user.js)

I installed it on Firefox, still had a few issues but was usable for the time being.

**Comment by fixer1234** [comment]
@enki-code Thanks.  I was going through withdrawal without my SOX.  :-)

**Comment by shu8** [comment]
@fixer1234 can you try installing [this version](https://github.com/soscripted/sox/raw/fix/sox.user.js) and see if is fixed for you now?

please delete the old version *first*!

**Comment by fixer1234** [comment]
@shu8, I rechecked this after loading the new version.  The pre-existing "Your Answer" box displays all three added features.  Opening an edit window on an existing post is missing the Find&Replace/Autocorrect buttons.

The SBS feature works.  The kbd feature works.  The bullet button just inserts a hyphen and space (it doesn't do any line breaks or positioning like the bullet list menu icon does, but I assume it is doing the intended action).

I was able to test Find&Replace/Autocorrect only on the "Your Answer" box, and this doesn't appear to work.  Find&Replace opens an entry panel where I entered some test values for find and replace (couldn't figure out what the Modifier box was for so I tried a few guesses and then left it blank).  The Go button didn't result in any action.

I couldn't get the Autocorrect feature to do anything (although this is a feature that isn't yet documented as far as what it's supposed to do).

**Comment by shu8** [comment]
@fixer1234 Find&Replace fixed in [latest version](https://github.com/soscripted/sox/raw/fix/sox.user.js).

The modifier box is for either `i`, `g`, or `m`; they're described in more detail at http://www.w3schools.com/jsref/jsref_obj_regexp.asp.

The autocorrect feature fixes any obvious, common typos. There's a list of them in the script. eg typing `teh` and clicking autocorrect should replace it to `the`, and simple things like that.

**Comment by fixer1234** [comment]
@shu8, I loaded the even newer, new v2.0.1.  These features are almost there.

All three features appear in the "Your answer" box, and all three features work there.

Opening an edit on an existing post, SBS and kbd/- both appear and both work.  However, Find&Replace/Autocorrect does not appear.

**Comment by shu8** [comment]
Should be fixed in [this even newer version](https://github.com/soscripted/sox/raw/fix/sox.user.js)

**Comment by fixer1234** [comment]
Success.  Newest, newer, new version looks like it fixes this.  All three features appear to be working in the Your Answer box and post edit windows.

**Comment by fixer1234** [comment]
Just encountered a case of some of the edit features not appearing in an edit conducted in a review queue with v2.0.1.  This was a case of editing an answer in the Late Answers review queue.  The kbd/list feature was present, but not sbs  or find&replace/autocorrect.   Console output:

```
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:6864
GET 
http://superuser.com/review/late-answers/580791 [HTTP/1.1 200 OK 161ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js [HTTP/1.1 304 Not Modified 69ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 29ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 28ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 83ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 66ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 45ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 41ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 21ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 14ms]
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 15ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 17ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:18:0
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 154ms]
SOX:  initializing SOX dialog sox.common.js:63:17
GET 
http://pixel.quantserve.com/pixel;r=998635711;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1475795599545;tzo=240;ref=;url=http%3A%2F%2Fsuperuser.com%2Freview%2Flate-answers%2F580791;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Review%20Late%20Answers%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Freview%2Flate-answers%2F580791 [HTTP/1.1 200 OK 130ms]
GET 
https://www.google-analytics.com/r/collect [HTTP/2.0 200 OK 32ms]
SOX:  injecting features into dialog sox.common.js:63:17
observe: .inbox-dialog sox.common.js:84:13
SOX Access Token: SET sox.common.js:46:1
observe: #wmd-redo-button sox.common.js:84:13
observe: [id^="wmd-redo-button"] sox.common.js:84:13
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 717ms]
vwof plugin, exception in ScreenWaveMedia: TypeError: video_data is undefined vwof.js:67:0
GET 
http://cdn.sstatic.net/Js/review.en.js [HTTP/1.1 304 Not Modified 15ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/ [HTTP/1.1 200 OK 127ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 200 OK 49ms]
GET 
http://superuser.com/content/img/progress-dots.gif [HTTP/1.1 200 OK 70ms]
POST 
XHR 
http://superuser.com/review/next-task/580791 [HTTP/1.1 200 OK 77ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 117ms]
GET 
https://www.gravatar.com/avatar/b9de025baed1081a7979d8bb9c208e88 [HTTP/2.0 304 Not Modified 22ms]
GET 
http://i.stack.imgur.com/RdTCS.png [HTTP/1.1 304 Not Modified 26ms]
GET 
https://www.gravatar.com/avatar/0b51840eb7be0a43d1d855b2f79bc0c8 [HTTP/2.0 304 Not Modified 24ms]
GET 
https://www.gravatar.com/avatar/48d3a2d84ee7e43fd731e57d9c704a4d [HTTP/2.0 304 Not Modified 18ms]
POST 
XHR 
http://superuser.com/client-timings [HTTP/1.1 204 No Content 34ms]
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 216ms]
no element found client-timings:1:1
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 25ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 50ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 80ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 85ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 83ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 87ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 93ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 62ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 98ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 102ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 100ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 104ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 104ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:2:40351
POST 
XHR 
http://superuser.com/review/inline-edit-post [HTTP/1.1 200 OK 34ms]
GET 
http://cdn.sstatic.net/Js/external-editor.en.js [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/Js/post-validation.en.js [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/Js/wmd.en.js [HTTP/1.1 200 OK 0ms]
fire: [id^="wmd-redo-button"] sox.common.js:91:29
GET 
http://cdn.sstatic.net/Sites/superuser/img/wmd-buttons.svg [HTTP/1.1 304 Not Modified 14ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 49ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```

Note that although there are a bunch of Ghostery entries, the site is whitelisted so Ghostery takes no action.

**Comment by fixer1234** [comment]
Update for v2.0.2Dev: In a non-review environment, Find&Replace|AutoCorrect is finicky.  

- Opening an edit window on a question or answer, that feature can take several seconds to appear.  But eventually, all of the features appear.

- Opening a page to a question thread, the Your Answer box shows all of the features.  However, if a question or answer is edited, upon closing the edit and exiting back to the page, the Find&Replace|AutoCorrect feature is removed (I saw it actually disappear about a second after closing an answer edit).  Reloading the page in the browser brings the feature back to the Your Answer box.

My previous post was about behavior in the review queues.  I just had a chance to retest editing a post in the Late Answers queue.  Only the kbd/list feature showed up when editing from within the review queue.  SBS and Find&Correct|AutoCorrect were missing.

**Comment by shu8** [comment]
@fixer1234 All of these issues should be fixed in [the latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js). Please could you install it and check whether it all works?

I haven't tested reviews yet, because there aren't any suggested edits on my active sites :P but I'll test that ASAP.

I'm leaving this open this time, until it's definitely fixed! :)

**Comment by fixer1234** [comment]
@shu8 Latest DEV version.  Haven't yet had occasion to test in the review queues, but in normal use, the feature looks like it's behaving well.  I'll report back on the review queues.

**Comment by fixer1234** [comment]
@shu8 Finally got an edit in a review queue.  That one is still the same.  Only the Kbd/List feature shows. SBS and Find&Replace/Autocorrect are missing in the review queue.

**Comment by shu8** [comment]
@fixer1234 turns out the enhancedEditor feature was entirely disabled on review. 

I've fixed both of these issues now (I think). Please can you [reinstall the dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) and test?

**Comment by fixer1234** [comment]
@shu8 Posted this on a different thread, but this dev version doesn't trigger the token.

**Comment by fixer1234** [comment]
@shu8 Finally had an edit review with a title edit (but just one, so I still haven't tested "next").  It had only an addition, and looked like this:

![su title edit](https://cloud.githubusercontent.com/assets/10065766/19871779/c74acc12-9f8c-11e6-96e0-6bcade224593.png)

I wasn't sure if all edits are supposed to show "before" and "after", or this is how it should appear.

**Comment by shu8** [comment]
@fixer1234 yeah, it **shouldn't** look like that. All edits should show it separately. But at least we know the problem now! I'll see if I can get it fixed :) (BTW: wrong issue!)

**Comment by fixer1234** [comment]
Oh, yeah.  Posted on the wrong issue.  It's a problem finding good help these days.  :-)

**Comment by fixer1234** [comment]
@shu8 Finally had occasion to edit in a review queue and all the features were there.  BTW, the long lag on displaying Find&Replace/Autocorrect is also gone.  Looks like all of the edit features are working well, and working everywhere.

**Comment by fixer1234** [comment]
@shu8 I won't reopen this one, but I came across a situation you could put on the back burner to look at someday.  If someone has proposed an edit that has not yet been approved, the post will indicate a pending edit.  From the post, users with sufficient rep can can click on the Edit button to review the proposed edit in place.  An option there is to improve the edit, which opens a small window for the editor.  The edit features now appear in that edit window, but the window may not even have the width for SBS to work properly.  Selecting SBS there gives you this:

![su improve edit](https://cloud.githubusercontent.com/assets/10065766/19878901/142854e6-9fc4-11e6-846b-8af0916626e2.png)

It's possible that you could get SBS working in this window, or it might be more practical to just not display the option in that situation.
