### ISSUE TITLE
Add a label on questions which are hot-network questions

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#75]
**Installed Version: 2.0.0  |  Environment: undefined**

**Expected Behavior**
>How do you expect the feature to work?
New feature this version, looked for behavior

**Actual Behavior**
>How is the feature currently behaving?
No obvious label or formatting on the main page or the thread.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?
Found a hot network question for SU in the list, went to the question and also found the question on the active questions page (several pages in, it was last modified yesterday).

**Comment by shu8** [comment]
You should see this:

![this](https://cloud.githubusercontent.com/assets/8850830/16544764/f31150a0-4109-11e6-80dc-ec363267c450.png)

on any of the 30 most recent hot network questions.

Try [visiting this question](http://codegolf.stackexchange.com/questions/84346/reverse-odd-sequences)

**Comment by enki-code** [comment]
I am unable to reproduce this on either Chrome or Firefox.

I'm getting the HOT label at the top right of the question as @shu8 pointed out.

**Comment by fixer1234** [comment]
I didn't see that on mine.  It's possible that the issue is common to what caused one of the other problems.  I had to remove v2.0.0 because the constant token nag screen made it impractical to use.  I'll re-check this feature when I load the version that patches that.

**Comment by fixer1234** [comment]
This feature wasn't included in the last v1.0.4 I had loaded, but it's listed in the preferences selection list on the one @enki-code  just provided a link to.  I checked a current question from the HNT list, and it isn't working for me on this version either.  So the problem apparently isn't associated with some other issue in v2.0.0 as I had speculated.  When you have time to get back to SOX, let me know what I can do to help diagnose it.

**Comment by shu8** [comment]
@fixer1234 hopefully this should also be fixed in the [user.js file in the `fix` branch](https://github.com/soscripted/sox/raw/fix/sox.user.js)

**Comment by fixer1234** [comment]
The "Hot" did appear with v2.0.1.

**Comment by fixer1234** [comment]
Newest, newer, new version: Feature works for some but not all HNQ.  Examples where the label does not appear:  

http://unix.stackexchange.com/questions/304694/udf-to-add-two-numbers-in-awk

http://academia.stackexchange.com/questions/75226/should-i-tell-students-that-its-my-first-time-teaching-the-course

http://networkengineering.stackexchange.com/questions/34117/does-having-a-longer-ethernet-cable-slow-your-connection

http://askubuntu.com/questions/814723/whats-the-difference-between-ssh-and-openssh-packages

Console output:

```
bg on Updatedbg.js:333:2
Object { status: "loading" }bg.js:334:2
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
bg on Updatedbg.js:333:2
Object { status: "loading", url: "http://askubuntu.com/questions/8147…" }bg.js:334:2
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
bg runtime Object { action: "check_shortcuts" }bg.js:75:5
bg runtime Object { id: 39, index: 2, windowId: 0, selected: true, highlighted: true, active: true, pinned: false, status: "loading", incognito: false, width: 1411, 6 more… }bg.js:76:5
sendRequest:  tab 39 Object { action: "update_shortcuts", msObj: "{"visible":{"enable":true,"key":"V"…" }bg.js:762:3
request end:  check_shortcutsbg.js:307:5
content script runtime.onMessage:  update_shortcutscontent_script.js:91:2
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.sox.common.js:18
SOX:  initializing SOX dialogsox.common.js:63:17
SOX:  injecting features into dialogsox.common.js:63:17
observe: .inbox-dialogsox.common.js:70:13
observe: .commentsox.common.js:70:13
SOX Access Token: CZFS8gYq1CSv9OYdwT7tiw))sox.common.js:46:13
observe: #wmd-redo-button-814737sox.common.js:70:13
observe: #wmd-redo-button-814723sox.common.js:70:13
observe: #wmd-redo-buttonsox.common.js:70:13
observe: [id^="wmd-redo-button"]sox.common.js:70:13
observe: .image-upload formsox.common.js:70:13
SOX Access Token: CZFS8gYq1CSv9OYdwT7tiw))sox.common.js:46:13
Array [ "superuser-139892", "superuser-1115827" ]sox.features.js:1326:17
observe: .share-tipsox.common.js:70:13
"SOX editReasonTooltip URL: http://askubuntu.com/posts/814723/revisions"sox.features.js:883:21
Object { context: <div#question.question>, length: 1, 1 more… }sox.features.js:884:21
SOX editReasonTooltip text: deleted 86 characters in body; edited tags; edited titlesox.features.js:885:21
no element found3be6:1:1
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
bg on Updatedbg.js:333:2
Object { status: "complete" }bg.js:334:2
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
bg runtime Object { action: "enable_selected" }bg.js:75:5
bg runtime Object { id: 39, index: 2, windowId: 0, selected: true, highlighted: true, active: true, pinned: false, status: "complete", incognito: false, width: 1411, 6 more… }bg.js:76:5
request end:  enable_selectedbg.js:307:5
fire: #wmd-redo-buttonsox.common.js:77:29
fire: [id^="wmd-redo-button"]sox.common.js:77:29
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.jquery.min.js:3:6598
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/panel.js:3525:3
not well-formedmessages.json:1:1
```

**Comment by enki-code** [comment]
I've never really cared for that feature and I wouldn't be the slightest bit upset if it were to be removed.

**Comment by shu8** [comment]
@fixer1234 This feature only works for the 30 most recent HNQs; try going on the first few in this list: http://stackexchange.com/; they should all work

**Comment by fixer1234** [comment]
@shu8 I didn't count, but it doesn't look like the HNQ list on the right side is over 30.  I did the test randomly picking from the then current list.  It's now several days later, so the specific questions I linked to, above, may no longer be on the list.  

That said, some strange results that might be diagnostic.  I went to your SE link and picked 5 questions.  Every one showed the HOT label.  Then I picked 5 from the current  HNQ list on the SU main page, right side display.  Only one of the five had the label.

So the feature works for some questions but not others.  Could the issue be that the list is frequently updated by SE, but what is displayed on the SU main page quickly becomes stale?  If the official list turns over continuously and the site main page isn't continuously updated, maybe most of whatever is displayed from say 5 or 10 minutes ago is no longer among the most recent 30.  

So if you open a question and see the label, you know that it is on HNQ at that moment, but it won't necessarily be on the main page list, and opening a question in the displayed HNQ list won't necessarily still be on it.  If HNQ is that transient, I'm not sure how useful the feature really is.  

Aside from the novelty value, the community moderation function could benefit from knowing that a question was on HNQ within the last several days (and that would also be more useful to users).  We can guess that wild view counts and outrageous upvotes probably means that.  But knowing definitively provides useful context.  I don't know how many questions are in HNQ in a 2 day period or whether there's a mechanism to capture them all, but if it could be done, that would be more useful.

If that's what's going on, I guess we can close this issue since that would mean that it's actually working as designed.

**Comment by shu8** [comment]
@fixer1234 AFAIK questions on the *sidebar* are in random order, and the ones on the homepage are in order.

The API doesn't provide HNQs, so I use an RSS feed which only gives me the 30 most recent ones.

I'll see if a new method has come, otherwise it's gonna stick like this; if you don't find it useful, please do disabled it.

**Comment by shu8** [comment]
@fixer1234 I found [a better method](http://meta.stackexchange.com/a/280365/260841), so *all* HNQs should work now in [v2.0.1d](https://github.com/soscripted/sox/raw/fix/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 I jumped right to v2.0.1f.  The new method is improved but still doesn't label every question showing in the site main page HNQ list on the side.  2 out of 6 random choices didn't get a label.  I suspect the list on the site pages just doesn't get updated with the same frequency as the master list, so some of the displayed questions are no longer on the list.  For this feature to be useful as more than a novelty, I suspect you would need to build your own rolling list that includes the most recent several days.  Since the feature is probably working as designed, feel free to close this one.
