### ISSUE TITLE
Show tags for the question an answer belongs to on search pages

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#95]
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**
Note: Firefox, not Chrome

**Expected Behavior**
>How do you expect the feature to work?
show question tags on answers on search results.  My recollection is that this feature was working in previous versions, but I wouldn't bet the farm on that.

**Actual Behavior**
>How is the feature currently behaving?
No tags on answers in any sort sequence.  The tags do appear on question posts in the results.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

I executed a search with a spec for just answer posts:

![su search no answer tags console](https://cloud.githubusercontent.com/assets/10065766/17647272/370630ea-61b8-11e6-893c-7b5c689b11b7.png)

**Steps to reproduce**
>What steps did you take to reproduce the issue?

**Comment by shu8** [comment]
@fixer1234 Fixed in [this new version](https://github.com/soscripted/sox/raw/fix/sox.user.js) :)

**Comment by fixer1234** [comment]
Installed newest, newer, new version.  This issue is back.  Console output:

```
bg on Updatedbg.js:333:2
Object { status: "loading" }bg.js:334:2
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
bg on Updatedbg.js:333:2
Object { status: "loading", url: "http://superuser.com/search?q=%5Bub…" }bg.js:334:2
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
bg runtime Object { action: "check_shortcuts" }bg.js:75:5
bg runtime Object { id: 31, index: 2, windowId: 0, selected: true, highlighted: true, active: true, pinned: false, status: "loading", incognito: false, width: 1411, 6 more… }bg.js:76:5
sendRequest:  tab 31 Object { action: "update_shortcuts", msObj: "{"visible":{"enable":true,"key":"V"…" }bg.js:762:3
request end:  check_shortcutsbg.js:307:5
content script runtime.onMessage:  update_shortcutscontent_script.js:91:2
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.sox.common.js:18
SOX:  initializing SOX dialogsox.common.js:63:17
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
SOX:  injecting features into dialogsox.common.js:63:17
observe: .inbox-dialogsox.common.js:70:13
SOX Access Token: CZFS8gYq1CSv9OYdwT7tiw))sox.common.js:46:13
observe: #wmd-redo-buttonsox.common.js:70:13
observe: [id^="wmd-redo-button"]sox.common.js:70:13
SOX Access Token: CZFS8gYq1CSv9OYdwT7tiw))sox.common.js:46:13
Array [ "superuser-139892", "superuser-1115827" ]sox.features.js:1326:17
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
bg on Updatedbg.js:333:2
Object { status: "complete" }bg.js:334:2
bg runtime Object { action: "enable_selected" }bg.js:75:5
bg runtime Object { id: 31, index: 2, windowId: 0, selected: true, highlighted: true, active: true, pinned: false, status: "complete", incognito: false, width: 1411, 6 more… }bg.js:76:5
request end:  enable_selectedbg.js:307:5
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.jquery.min.js:3:6598
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
Error: Could not establish connection. Receiving end does not exist.(unknown)
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/panel.js:3525:3
not well-formedmessages.json:1:1
```

**Comment by shu8** [comment]
@fixer1234 No repro for me in FF or Chrome. If this still happens, please enable the 'NET' tab in the console and refresh and paste the log here, and could you take a screenshot(s) of the 'Network' tab on the top right of the console pane,

**Comment by fixer1234** [comment]
@shu8 the console output I pasted above was captured as you describe.  I'm not understanding what you're looking for with the screenshot.  On mine, the Net tab is on the left.  But are you just looking for verification that the tab or options have been properly selected?

**Comment by fixer1234** [comment]
```
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:5142
GET 
http://superuser.com/search [HTTP/1.1 200 OK 108ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js [HTTP/1.1 304 Not Modified 30ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 11ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 15ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 54ms]
GET 
http://static.adzerk.net/ados.js [HTTP/1.1 304 Not Modified 21ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 24ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 20ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 18ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 13ms]
GET 
http://cdn.sstatic.net/img/favicons-sprite16.png [HTTP/1.1 304 Not Modified 13ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 12ms]
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 16ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 11ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:18:0
GET 
http://engine.adzerk.net/ados [HTTP/1.1 200 OK 90ms]
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 16ms]
SOX:  initializing SOX dialog sox.common.js:63:17
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 14ms]
GET 
http://pixel.quantserve.com/pixel;r=1600786396;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1471986403104;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Fquestions%2F1116516%2Fwhat-would-happen-if-you-put-multiple-pcie-cards-in-one-pcie-slot;url=http%3A%2F%2Fsuperuser.com%2Fsearch%3Fq%3D%255Bssd%255D%2Bis%253Aa;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Posts%20containing%20'is%3Aa'%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fsearch%3Fq%3D%5Bssd%5D%2Bis%3Aa [HTTP/1.1 200 OK 28ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 200 OK 0ms]
GET 
http://cdn.sstatic.net/img/favicons-sprite16.png [HTTP/1.1 200 OK 0ms]
SOX:  injecting features into dialog sox.common.js:63:17
observe: .inbox-dialog sox.common.js:70:13
SOX Access Token: XJUIjR9HFt16u5mikBfSBg)) sox.common.js:46:1
observe: #wmd-redo-button sox.common.js:70:13
observe: [id^="wmd-redo-button"] sox.common.js:70:13
SOX Access Token: XJUIjR9HFt16u5mikBfSBg)) sox.common.js:46:1
Array [  ] sox.features.js:1326:17
GET 
XHR 
https://api.stackexchange.com/2.2/questions/285872;345299;347844;285872;220968;140393;69196;7955;559823;492673;506063;500120;512166;266178;262753;467659;767333;782088;735098;923081;639171;220291;775059;775059;760850;616033;432668;157488;254068;319815;367288;229201;69196;518605;538842;492673;406120;423659;399491;441016;653184;536427;1021859;1061229;755895;536213;767333;804799;831569;69196 [HTTP/1.1 400 Bad Request 64ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/10121;86978;52492;108308;40350;3588;9059;109675;73918;144607;24010;94537;69290;66902;83694;304648;345677;117592;138343;46334;58510;340046;4236;214597;23133;37440;92181;63552;4386;168423;170017;150754;85849;116375;94136;144701;4487;33200;137786;573485;289281;175125;167436;300968;383643;17492 [HTTP/1.1 200 OK 75ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 73ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 380ms]
vwof plugin, exception in ScreenWaveMedia: TypeError: video_data is undefined vwof.js:67:0
GET 
http://static.adzerk.net/Extensions/adFeedback.js [HTTP/1.1 304 Not Modified 16ms]
GET 
http://static.adzerk.net/Extensions/adFeedback.css [HTTP/1.1 304 Not Modified 26ms]
GET 
http://engine.adzerk.net/i.gif [HTTP/1.1 200 OK 34ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 351ms]
GET 
http://static.adzerk.net/Advertisers/2c1568aae6d8464bb67a1eaecae6e3ae.png [HTTP/1.1 304 Not Modified 17ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:6598
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 62ms]
POST 
XHR 
http://superuser.com/client-timings [HTTP/1.1 204 No Content 28ms]
no element found client-timings:1:1
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 22ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 34ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 53ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 64ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 62ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 39ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 72ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 77ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 61ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 78ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 83ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 88ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 92ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 94ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 97ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 101ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
```

**Comment by fixer1234** [comment]
I loaded v2.0.1a after posting the comment above.  Looks like another one where whatever you did replenished the magic smoke.  The feature is working again.

**Comment by fixer1234** [comment]
Magic smoke is gone, again, with v2.0.1b.  No more tags on answers.
```
GET 
XHR 
https://s.yimg.com/tq/irisloadtest/test-config.json [HTTP/2.0 200 OK 0ms]
GET 
XHR 
https://us-mg5.mail.yahoo.com/ws/v3/mailboxes/@.id==VjJ-h2fxycDNCcqfC8zTxqftXAhTDiS-YrRKp37O5zidoYsGflwlerietZDFWcFrQRNv/folders [HTTP/2.0 200 OK 133ms]
bg on Updatedbg.js:333:2
Object { status: "loading" }bg.js:334:2
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
GET 
http://superuser.com/search [HTTP/1.1 200 OK 123ms]
bg on Updatedbg.js:333:2
Object { status: "loading", url: "http://superuser.com/search?q=%5Bub…" }bg.js:334:2
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js [HTTP/1.1 304 Not Modified 41ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 21ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 25ms]
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
GET 
http://static.adzerk.net/ados.js [HTTP/1.1 304 Not Modified 25ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 16ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 30ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 33ms]
bg runtime Object { action: "check_shortcuts" }bg.js:75:5
bg runtime Object { id: 30, index: 2, windowId: 0, selected: true, highlighted: true, active: true, pinned: false, status: "loading", incognito: false, width: 1411, 6 more… }bg.js:76:5
sendRequest:  tab 30 Object { action: "update_shortcuts", msObj: "{"visible":{"enable":true,"key":"V"…" }bg.js:762:3
request end:  check_shortcutsbg.js:307:5
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 48ms]
content script runtime.onMessage:  update_shortcutscontent_script.js:91:2
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.sox.common.js:18
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 20ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 21ms]
GET 
http://cdn.sstatic.net/img/favicons-sprite16.png [HTTP/1.1 304 Not Modified 19ms]
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 18ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 20ms]
SOX:  initializing SOX dialogsox.common.js:63:17
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 16ms]
SOX:  injecting features into dialogsox.common.js:63:17
observe: .inbox-dialogsox.common.js:70:13
SOX Access Token: wf(MLeZcS61ToIOti1g59Q))sox.common.js:46:13
observe: #wmd-redo-buttonsox.common.js:70:13
observe: [id^="wmd-redo-button"]sox.common.js:70:13
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 17ms]
GET 
http://engine.adzerk.net/ados [HTTP/1.1 200 OK 121ms]
GET 
http://pixel.quantserve.com/pixel;r=1990694587;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-43830223-1458445567807;ns=0;ce=1;cm=;je=1;sr=1600x900x24;enc=n;dst=1;et=1472087871622;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Fquestions%2F1117279%2Fcapture-info-from-one-excel-workbook-and-add-totals-in-another;url=http%3A%2F%2Fsuperuser.com%2Fsearch%3Fq%3D%255Bubuntu%255D%2Bis%253Aa;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Posts%20containing%20'is%3Aa'%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fsearch%3Fq%3D%5Bubuntu%5D%2Bis%3Aa [HTTP/1.1 200 OK 33ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions/340467;495651;462120;260056;260056;273753;277073;390273;390273;339418;128751;428901;429817;179460;179460;190246;197477;213838;112132;116367;117416;135876;143791;147572;142111;173083;89433;90471;105824;105660;37602;44280;52973;59767;66268;449241;768971;190827;313601;883314;759278;735691;608975;750782;857684;615791;630609;581063;549958;564807 [HTTP/1.1 400 Bad Request 64ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/160048;167288;79715;46328;1686;69290;79101;117612;52461;99341;68918;118184;89018;36638;4129;310;51788;56537;26210;4386;29679;31910;35521;45258;82982;8672;22963;1931;14270;12567;3157;50067;7829;10554;16820;148355;413239;8804;143775;192966;361013;44887;231962;61614;365120;105557;81537;82879;94136;206472 [HTTP/1.1 200 OK 101ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 607ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 23ms]
GET 
http://static.adzerk.net/Extensions/adFeedback.js [HTTP/1.1 304 Not Modified 21ms]
GET 
http://static.adzerk.net/Extensions/adFeedback.css [HTTP/1.1 304 Not Modified 24ms]
GET 
http://engine.adzerk.net/i.gif [HTTP/1.1 200 OK 360ms]
GET 
http://area51.stackexchange.com/ads/proposal/js [HTTP/1.1 200 OK 28ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 63ms]
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
GET 
http://cdn.sstatic.net/area51/Img/bg-area51-ad-commitment.png [HTTP/1.1 304 Not Modified 64ms]
bg on Updatedbg.js:333:2
Object { status: "complete" }bg.js:334:2
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
bg runtime Object { action: "enable_selected" }bg.js:75:5
bg runtime Object { id: 30, index: 2, windowId: 0, selected: true, highlighted: true, active: true, pinned: false, status: "complete", incognito: false, width: 1411, 6 more… }bg.js:76:5
request end:  enable_selectedbg.js:307:5
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.jquery.min.js:3:6598
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/panel.js:3525:3
not well-formedmessages.json:1:1
Error: Could not establish connection. Receiving end does not exist.(unknown)
```
The first couple of lines appeared before I refreshed the search page after clearing the console.

**Comment by shu8** [comment]
@fixer1234 Can you try installing [v2.0.1c](https://github.com/soscripted/sox/raw/fix/sox.user.js) and check if the errors still remain?

Also, are you free to [chat](https://gitter.im/soscripted/sox?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for half an hour or so at any time? I'd really like to get these issues sorted, and chatting should hopefully be quicker :)

**Comment by shu8** [comment]
@fixer1234 If you haven't already tried, please skip that version and use [v2.0.1d](https://github.com/soscripted/sox/raw/fix/sox.user.js) instead :)

**Comment by fixer1234** [comment]
@shu8  Jumped to v2.0.1f.  Magic smoke is replenished.  Closing this issue.  re: chat -- I'll be in and out.  When is a good time for you?

**Comment by shu8** [comment]
@fixer1234 If you can do today, how about in half an hour? (20:00 GMT+1). Otherwise tomorrow around 16:00 till 18:00 GMT+1?

**Comment by fixer1234** [comment]
@shu8 Converting to GMT time is too much math for my brain.  :-)    I just found this message.  I'll be around for awhile, if you're available.

**Comment by shu8** [comment]
@fixer1234 now?

**Comment by fixer1234** [comment]
@shu8 v2.0.1g: magic smoke gone again.

**Comment by shu8** [comment]
@fixer1234 Can you dump the console when running [v2.0.1k](https://github.com/soscripted/sox/raw/fix/sox.user.js) please?

**Comment by fixer1234** [comment]
```
GET 
http://superuser.com/search [HTTP/1.1 200 OK 125ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js [HTTP/1.1 304 Not Modified 157ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 30ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 39ms]
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 64ms]
GET 
http://static.adzerk.net/ados.js [HTTP/1.1 304 Not Modified 46ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 83ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 73ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 23ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 14ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 200 OK 51ms]
GET 
http://cdn.sstatic.net/img/favicons-sprite16.png [HTTP/1.1 304 Not Modified 17ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.sox.common.js:18
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 20ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 15ms]
SOX:  initializing SOX dialogsox.common.js:63:17
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 64ms]
SOX:  injecting features into dialogsox.common.js:63:17
"Getting From API with URL: https://api.stackexchange.com/2.2/questions/571970;576182;843104;478832;511354;489114;350698;429256;359620;359620;462952;259645;271432;269096;116367;105823;286226;291136;291269;293379;235496;205441;241139;160835;161277;182864;301944;124948;124948;112109;112109;142111;86948;90471;116502;34988;37595;38474;38474;64865;62892;70466;70466;70466;66909;77667;69462;701804;418338;271584?order=desc&sort=creation&pagesize=60&site=superuser"sox.common.js:67:13
SOX Access Token: SETsox.common.js:46:13
Object {  }sox.features.js:1470:13
Object {  }sox.features.js:1471:13
0sox.features.js:1472:13
GET 
http://engine.adzerk.net/ados [HTTP/1.1 200 OK 191ms]
GET 
http://pixel.quantserve.com/pixel;r=1678725011;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-1541000686-1462331864564;ns=0;ce=1;cm=;je=1;sr=1787x1005x24;enc=n;dst=1;et=1472430772073;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Ftags;url=http%3A%2F%2Fsuperuser.com%2Fsearch%3Fq%3D%255Bubuntu%255D%2Bis%253Aa;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Posts%20containing%20'is%3Aa'%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fsearch%3Fq%3D%5Bubuntu%5D%2Bis%3Aa [HTTP/1.1 200 OK 72ms]
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 85ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/160454;74338;387726;190174;167288;156043;52492;126807;103272;104424;151431;72407;74377;78078;48645;46165;81684;8804;50697;11771;310;28756;72339;2249;5026;39637;73918;30310;593;20077;28074;7730;2226;18112;1218;723;9352;9571;12517;591;10452;2855;16752;16639;18532;74802;125561;20110 [HTTP/1.1 200 OK 100ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 110ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions/571970;576182;843104;478832;511354;489114;350698;429256;359620;359620;462952;259645;271432;269096;116367;105823;286226;291136;291269;293379;235496;205441;241139;160835;161277;182864;301944;124948;124948;112109;112109;142111;86948;90471;116502;34988;37595;38474;38474;64865;62892;70466;70466;70466;66909;77667;69462;701804;418338;271584 [HTTP/1.1 400 Bad Request 28ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 28ms]
SOX Error: error Bad Requestsox.common.js:73:21
GET 
http://static.adzerk.net/Extensions/adFeedback.js [HTTP/1.1 304 Not Modified 53ms]
GET 
http://static.adzerk.net/Extensions/adFeedback.css [HTTP/1.1 304 Not Modified 38ms]
GET 
http://engine.adzerk.net/i.gif [HTTP/1.1 200 OK 47ms]
GET 
http://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 47ms]
GET 
http://stackexchange.com/ads/beta-question/js [HTTP/1.1 200 OK 29ms]
GET 
http://sstatic.net/stackexchange/Img/beta-ad-bg.jpg [HTTP/1.1 304 Not Modified 107ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 75ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.jquery.min.js:3:6598
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON datasox.features.js:1537:29
GET 
XHR 
https://github.com/soscripted/sox/suggestions/issue/171027173 [HTTP/1.1 200 OK 201ms]
Content Security Policy: The page's settings blocked the loading of a resource at about:blank ("base-uri https://github.com").(unknown)
GET 
https://assets-cdn.github.com/images/icons/emoji/feelsgood.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/finnadie.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/fu.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/goberserk.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/godmode.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/hurtrealbad.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/neckbeard.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/rage1.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/rage2.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/rage3.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/rage4.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/shipit.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/suspect.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/bowtie.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/metal.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/octocat.png [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/trollface.png [HTTP/1.1 200 OK 0ms]
```

I tried the first bad request and got throttled:
```
https://api.stackexchange.com/2.2/questions/571970;576182;843104;478832;511354;489114;350698;429256;359620;359620;462952;259645;271432;269096;116367;105823;286226;291136;291269;293379;235496;205441;241139;160835;161277;182864;301944;124948;124948;112109;112109;142111;86948;90471;116502;34988;37595;38474;38474;64865;62892;70466;70466;70466;66909;77667;69462;701804;418338;271584%20[HTTP/1.1%20400
{"error_id":502,"error_message":"too many requests from this IP, more requests available in 20055 seconds","error_name":"throttle_violation"}
```

**Comment by fixer1234** [comment]
@shu8 Loaded v2.0.1L and this feature is working again.  I'll close this.
